[package]
name = "client-cpp"
version = "0.1.0"
authors = ["venslu <1262612838@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "tikv_client_rust"
crate-type = ["staticlib"]

[dependencies]
anyhow = "1.0"
cxx = "1.0.18"
futures = "0.3"
tikv-client = "0.0.0"
grpcio = { version = "0.6", features = ["openssl"] }
#tikv-client = { git = "https://github.com/tikv/client-rust.git", branch = "master" }
